version: '3.7'
services:
  db:
    container_name: moraru_db
    image: postgres:12-alpine
    volumes:
      - moraru_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_USER=admin
      - POSTGRES_DB=moraru
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  moraru_db: {}
